version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: payment-authorize_app
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8090:8090"
    volumes:
      - ./:/var/www/app
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    working_dir: /var/www/app
    entrypoint: "php -S 0.0.0.0:8090"
    links:
      - db

  db:
    container_name: payment-authorize_db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payment_authorize
    ports:
      - "3307:3306"